name: .NET

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build-Dto
      run: dotnet build Release FinFolio.PortFolio.DTO/FinFolio.PortFolio.DTO.csproj --configuration --no-restore 
    - name: Build-PortFolioRepository
      run: dotnet build Release FinFolio.ClientRepository/FinFolio.PortFolioRepository.csproj --configuration --no-restore 
    - name: Build-PortFolioCore
      run: dotnet build Release FinFolio.ClientCore/FinFolio.PortFolioCore.csproj --configuration --no-restore 
    - name: Build-PortFolioWebApi
      run: dotnet build Release FinFolio.ClientServiceFunctions/FinFolio.PortFolio.WebAPI.csproj --configuration --no-restore 
    - name: Publish WebApi Artifacts
      run:  dotnet publish -c Release -o ../FinFolioWebApi -r linux-x64 --self-contained true /p:UseAppHost=true
   
