# This is a basic workflow to help you get started with Actions

name: Manually Publish WebAPI Functions to Azure

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  AZURE_FUNC_NAME: FinFolioWebApi
  AZURE_FUNC_PACKAGE_PATH: 'FinFolioWebApi' 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a se quence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
         dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore   
        
      - name: Publish WebApi Artifacts
        run:  dotnet publish FinFolio.ClientServiceFunctions/FinFolio.PortFolio.WebAPI.csproj -c Release -o ../FinFolioWebApi
     # - uses: vimtor/action-zip@v1
       # with:
         #files: FinFolioWebApi
         #recursive: false
         #dest: FinFolioWebApi.zip
      
      - name: Azure-Functions-Deploy-Action
        uses: Azure/functions-action@v1.4.6
        with:
          app-name: ${{env.AZURE_FUNC_NAME}}
          package:  ../FinFolioWebApi
          publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
